/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosco;

import datos.Cola;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class ApuntarseImpro extends javax.swing.JPanel {

    private Ventana v;
    private Impro padre;
    private ArrayList<String> cola;

    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }

    public Impro getPadre() {
        return padre;
    }

    public void setPadre(Impro padre) {
        this.padre = padre;
    }
    
    
    
    /**
     * Creates new form ApuntarseImpro
     */
    public ApuntarseImpro(Impro impro) {
        initComponents();
        padre = impro;
        lbError.setVisible(false);
        cola = Cola.getCola();
        
        if(cola.size() > 0) {
            lbAviso.setVisible(false);
        }
        lbExiste.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnPortada = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lbError = new javax.swing.JLabel();
        lbAviso = new javax.swing.JLabel();
        lbExiste = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("APUNTARSE A LA IMPROVISACIÓN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        btnPortada.setBackground(new java.awt.Color(255, 100, 0));
        btnPortada.setText("Portada");
        btnPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortadaActionPerformed(evt);
            }
        });
        add(btnPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, 30));

        btnAtras.setBackground(new java.awt.Color(255, 200, 100));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 30));

        jLabel3.setText("Escribe el nombre con el que quieras apuntarte. Una vez te registres, no podrás borrarte.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtNombre.setText("Escribe aquí tu nombre");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 280, -1));

        btnEnviar.setBackground(new java.awt.Color(100, 255, 100));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 570, -1));

        lbError.setForeground(new java.awt.Color(255, 0, 0));
        lbError.setText("Por favor, rellena el cambio de nombre.");
        add(lbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        lbAviso.setForeground(new java.awt.Color(0, 0, 255));
        lbAviso.setText("Aviso: la cola está vacía. Si te apuntas, ¡Serás el próximo en actuar!");
        add(lbAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lbExiste.setForeground(new java.awt.Color(255, 0, 0));
        lbExiste.setText("El nombre introducido ya existe en la cola.");
        add(lbExiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortadaActionPerformed
        this.v.getContentPane().setVisible(false);
        padre.getPadre().setVisible(true);
        v.setContentPane(padre.getPadre());
    }//GEN-LAST:event_btnPortadaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.v.getContentPane().setVisible(false);
        padre.setVisible(true);
        v.setContentPane(padre);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        lbExiste.setVisible(false);
        String nombre = txtNombre.getText();
        if (nombre.isEmpty() || (nombre == null)) {
            lbError.setVisible(true);
        }
        boolean existe = false;
        for (String nombreCola : cola) {
            if (nombreCola.equals(nombre)) {
                existe = true;
            }
        }
        if(existe) {
            lbExiste.setVisible(true);
        }
        else {
            this.v.getContentPane().setVisible(false);
            ColaImpro pl =new ColaImpro(nombre, this);
            pl.setVisible(true);
            pl.setV(this.v);
            this.v.setContentPane(pl);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        if(txtNombre.getText().equals("Escribe aquí tu nombre")) {
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnPortada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbAviso;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbExiste;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
