/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosco;

import datos.Actuacion;
import java.util.ArrayList;

/**
 *
 * @author Usuario
 */
public class Bienvenido extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenido
     */
    private Ventana v;
    private ArrayList<Actuacion> actuaciones;

    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }
    
    public Bienvenido(ArrayList<Actuacion> actuaciones) {
        initComponents();
        this.actuaciones = actuaciones;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDO AL TEATRO LOPE DE VEGA DE VIGO");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 440, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.v.getContentPane().setVisible(false);
        Portada pl =new Portada(actuaciones);
        pl.setVisible(true);
        pl.setV(this.v);
        this.v.setContentPane(pl);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
