/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kiosco;

import datos.Actuacion;
import javax.swing.JPanel;
import tienda.ElegirZona;

/**
 *
 * @author Usuario
 */
public class Espectaculo extends javax.swing.JPanel {

    private Ventana v;
    private javax.swing.JPanel padre;
    private Actuacion a;

    
    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }

    public JPanel getPadre() {
        return padre;
    }

    public void setPadre(JPanel padre) {
        this.padre = padre;
    }
    
    public Espectaculo(javax.swing.JPanel padre, Actuacion actuacion) {
        initComponents();
        this.padre = padre;
        this.a = actuacion;
        
        colocarEtiquetas();
    }
    
    public void colocarEtiquetas() {
        lbNombre.setText(a.getNombre());
        lbTipo.setText(a.getTipo());
        lbGenero.setText(a.getGenero());
        lbDescripcion.setText(a.getDescripcion());
        lbFechahora.setText(a.getFechahora());
        String aforo = a.getDisponibleTotal() + " (" + a.getDisponiblePatio() + " de Patio, " +  a.getDisponiblePalco() + " de Palco, " + a.getDisponibleVR() + " de Visibilidad Reducida)";
        lbAforo.setText(aforo);
        lbPrecio.setText(Double.toString(a.getPrecio()) + " €");
        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource(a.getImagen())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgEspectaculo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        lbDescripcion = new javax.swing.JLabel();
        lbFechahora = new javax.swing.JLabel();
        lbAforo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fundacion-caja-castellon-tortuga.jpg"))); // NOI18N
        add(imgEspectaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("DATOS DEL ESPECTÁCULO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        btnComprar.setBackground(new java.awt.Color(100, 255, 100));
        btnComprar.setText("COMPRAR ENTRADAS");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 500, -1));

        btnAtras.setBackground(new java.awt.Color(255, 200, 100));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        jPanel1.setBackground(new java.awt.Color(180, 180, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Precio (Adulto):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setText("Tipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setText("Descripción:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setText("Fecha y hora:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel8.setText("Aforo disponible:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel9.setText("Género:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lbPrecio.setText("(PRECIO)");
        jPanel1.add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        lbNombre.setText("(NOMBRE)");
        jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lbTipo.setText("(TIPO)");
        jPanel1.add(lbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        lbGenero.setText("(GENERO)");
        jPanel1.add(lbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lbDescripcion.setText("(DESCRIPCION)");
        jPanel1.add(lbDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        lbFechahora.setText("(FECHAHORA)");
        jPanel1.add(lbFechahora, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        lbAforo.setText("(AFORO)");
        jPanel1.add(lbAforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 500, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        this.v.getContentPane().setVisible(false);
        ElegirZona pl =new ElegirZona(this, a);
        pl.setVisible(true);
        pl.setV(this.v);
        this.v.setContentPane(pl);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.v.getContentPane().setVisible(false);
        padre.setVisible(true);
        v.setContentPane(padre);
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel imgEspectaculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAforo;
    private javax.swing.JLabel lbDescripcion;
    private javax.swing.JLabel lbFechahora;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbTipo;
    // End of variables declaration//GEN-END:variables
}
