/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import datos.Actuacion;
import static java.lang.Math.round;
import kiosco.Espectaculo;
import kiosco.Kiosco;
import kiosco.Ventana;

/**
 *
 * @author Usuario
 */
public class CodigoDescuento extends javax.swing.JPanel {

    private Ventana v;
    private ElegirCantidad padre;
    private Espectaculo ventanaEspectaculo;
    private Actuacion a;
    private double precio;
    private int totalEntradas;
    private String zona;
    private boolean introducido;

    public Actuacion getA() {
        return a;
    }

    public void setA(Actuacion a) {
        this.a = a;
    }

    
    
    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }

    public ElegirCantidad getPadre() {
        return padre;
    }

    public void setPadre(ElegirCantidad padre) {
        this.padre = padre;
    }

    public Espectaculo getVentanaEspectaculo() {
        return ventanaEspectaculo;
    }

    /**
     * Creates new form CodigoDescuento
     */
    public void setVentanaEspectaculo(Espectaculo ventanaEspectaculo) {    
        this.ventanaEspectaculo = ventanaEspectaculo;
    }

    public CodigoDescuento(Ventana v, ElegirCantidad padre, Espectaculo ventanaEspectaculo, Actuacion a, double precio, int totalEntradas, String zona) {
        initComponents();
        
        this.v = v;
        this.padre = padre;
        this.ventanaEspectaculo = ventanaEspectaculo;
        this.a = a;
        this.precio = precio;
        this.totalEntradas = totalEntradas;
        this.zona = zona;
        
        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource(a.getImagen())));
        lbPrecioTotal.setText(Kiosco.round(this.precio, 2) + " €");
        lbPremio.setVisible(false);
        lbNoPremio.setVisible(false);
        introducido = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContinuar = new javax.swing.JButton();
        imgEspectaculo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbPrecioTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNoPremio = new javax.swing.JLabel();
        lbPremio = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContinuar.setBackground(new java.awt.Color(100, 255, 100));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 550, -1));

        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fundacion-caja-castellon-tortuga.jpg"))); // NOI18N
        add(imgEspectaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("TOTAL:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        lbPrecioTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbPrecioTotal.setForeground(new java.awt.Color(0, 0, 255));
        lbPrecioTotal.setText("(PRECIO)");
        add(lbPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 100, 0));
        btnCancelar.setText("Cancelar compra");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        btnAtras.setBackground(new java.awt.Color(255, 200, 100));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("CÓDIGO DE DESCUENTO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(180, 180, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Si posees algún código promocional, puedes introducirlo aquí:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtCodigo.setText("Tu código");
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCodigoMouseClicked(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 240, -1));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel3.setText("(PISTA: Prueba con 1234)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel4.setText("Solo podrás introducirlo una vez.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 430, 130));

        lbNoPremio.setForeground(new java.awt.Color(255, 0, 0));
        lbNoPremio.setText("Lo sentimos, el código no es válido.");
        add(lbNoPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        lbPremio.setForeground(new java.awt.Color(0, 255, 0));
        lbPremio.setText("¡Has obtenido un descuento del 10%!");
        add(lbPremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        this.v.getContentPane().setVisible(false);
        ConfirmarPago pl =new ConfirmarPago(v, this, ventanaEspectaculo, a, precio, totalEntradas, zona);
        pl.setVisible(true);
        pl.setV(this.v);
        this.v.setContentPane(pl);
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.v.getContentPane().setVisible(false);
        ventanaEspectaculo.getPadre().setVisible(true);
        v.setContentPane(ventanaEspectaculo.getPadre());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed

        this.v.getContentPane().setVisible(false);
        padre.setVisible(true);
        v.setContentPane(padre);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseClicked
        if(txtCodigo.getText().equals("Tu código")) {
            txtCodigo.setText("");
        }
        
    }//GEN-LAST:event_txtCodigoMouseClicked

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (txtCodigo.getText().equals("1234") && (!introducido)) {
           precio *= 0.9;
           lbPrecioTotal.setText(Kiosco.round(this.precio, 2) + " €");
           lbPremio.setVisible(true);
            lbNoPremio.setVisible(false);
            introducido = true;
        }
        else {
            txtCodigo.setText("");
            lbPremio.setVisible(false);
            lbNoPremio.setVisible(true);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel imgEspectaculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNoPremio;
    private javax.swing.JLabel lbPrecioTotal;
    private javax.swing.JLabel lbPremio;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
