/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tienda;

import kiosco.Espectaculo;
import kiosco.Ventana;
import datos.Actuacion;
import static java.lang.Math.round;

/**
 *
 * @author Usuario
 */
public class ElegirZona extends javax.swing.JPanel {

    private Ventana v;
    private Espectaculo ventanaEspectaculo;
    private Actuacion a;
    private double precioPatio;
    private double precioVR;
    private double precioPalco;
    
    /**
     * Creates new form ElegirZona
     */
    public ElegirZona(Espectaculo ventanaEspectaculo, Actuacion a) {
        initComponents();
        
        this.ventanaEspectaculo = ventanaEspectaculo;
        this.a = a;
        grupoRadio.add(radioPatio);
        grupoRadio.add(radioPalco);
        grupoRadio.add(radioVR);
        
        precioPatio = a.getPrecio() * 1.2;
        precioPalco = a.getPrecio();
        precioVR = a.getPrecio() * 0.7;
        
        radioPatio.setText("Patio (Precio: " + precioPatio + " €, Disponibles: " + a.getDisponiblePatio() + ")");
        radioPalco.setText("Palco (Precio: " + precioPalco + " €, Disponibles: " + a.getDisponiblePalco() + ")");
        radioVR.setText("Palco, VR (Precio: " + precioVR + " €, Disponibles: " + a.getDisponibleVR() + ")");
        
        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource(a.getImagen())));
        
    }

    public Espectaculo getVentanaEspectaculo() {
        return ventanaEspectaculo;
    }

    public void setVentanaEspectaculo(Espectaculo ventanaEspectaculo) {
        this.ventanaEspectaculo = ventanaEspectaculo;
    }

    public Actuacion getA() {
        return a;
    }

    public void setA(Actuacion a) {
        this.a = a;
    }

    public Ventana getV() {
        return v;
    }

    public void setV(Ventana v) {
        this.v = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadio = new javax.swing.ButtonGroup();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imgEspectaculo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioPatio = new javax.swing.JRadioButton();
        radioPalco = new javax.swing.JRadioButton();
        radioVR = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setBackground(new java.awt.Color(255, 100, 0));
        btnCancelar.setText("Cancelar compra");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("ELIGE UNA ZONA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mapateatro.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        imgEspectaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fundacion-caja-castellon-tortuga.jpg"))); // NOI18N
        add(imgEspectaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(180, 180, 180));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioPatio.setBackground(new java.awt.Color(180, 180, 180));
        radioPatio.setSelected(true);
        radioPatio.setText("Patio");
        jPanel1.add(radioPatio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        radioPalco.setBackground(new java.awt.Color(180, 180, 180));
        radioPalco.setText("Palco");
        jPanel1.add(radioPalco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        radioVR.setBackground(new java.awt.Color(180, 180, 180));
        radioVR.setText("Palco VR");
        jPanel1.add(radioVR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 320, 220));

        btnContinuar.setBackground(new java.awt.Color(100, 255, 100));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 550, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.v.getContentPane().setVisible(false);
        ventanaEspectaculo.getPadre().setVisible(true);
        v.setContentPane(ventanaEspectaculo.getPadre());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        double nuevoPrecio = 0;
        int entradasMax = 10;
        String zona = null;
        if(radioPatio.isSelected()) {
            nuevoPrecio = precioPatio;
            zona = "patio";
            entradasMax = a.getDisponiblePatio();
        }
        else if(radioPalco.isSelected()) {
            nuevoPrecio = precioPalco;
            zona = "palco";
            entradasMax = a.getDisponiblePalco();
        }
        else if(radioVR.isSelected()) {
            nuevoPrecio = precioVR;
            zona = "vr";
            entradasMax = a.getDisponibleVR();
        }
        
        this.v.getContentPane().setVisible(false);
        ElegirCantidad pl =new ElegirCantidad(this, ventanaEspectaculo, a, nuevoPrecio, entradasMax, zona);
        pl.setVisible(true);
        pl.setV(this.v);
        this.v.setContentPane(pl);
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup grupoRadio;
    private javax.swing.JLabel imgEspectaculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioPalco;
    private javax.swing.JRadioButton radioPatio;
    private javax.swing.JRadioButton radioVR;
    // End of variables declaration//GEN-END:variables
}
